# (c) Srevin Saju 2020. All rights reserved 
# Licensed under MIT License
# Continuous Integration to release configured AppImages for Element (Riot) desktop client

name: Continuous

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]


jobs:
  centos:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Configure Go-AppImagetool
        run: |
          export ARCH=amd64
          bash -ex ./scripts/build.sh
          ls
          mkdir dist-ss
          mv /tmp/go/src/appimagetool-*.AppImage dist-ss/
      - name: Upload Appimage
        uses: actions/upload-artifact@v1.0.0
        with:
          name: AppImageTool-build
          path: 'dist-ss'

  Release:
    needs: [centos]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: AppImageTool-build

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/dev'
      with:
        automatic_release_tag: continuous
        title: Beta AppImage Release
        prerelease: true
        files: |
          AppImageTool-build

        repo_token: ${{ secrets.GITHUB_TOKEN }}
 
